### ISSUE TITLE
Cant build the site by running yarn dev

### ISSUE THREAD

**Issue by ymolists** [gitpod-io/website#1558]
Hi All

Thank you so much for open sourcing this website. I am trying to learn svelte and this is a super nice opportunity to see people using svelte and learn from them !!!

I am trying to build it but i am getting the below error. I hope this rings a bell :-)

```
$node -v
v16.13.1

$git sha
4c3b280f29c30e09097db1746b27eb043d29e015

$lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.04
Release:        21.04
Codename:       hirsute

$yarn dev
yarn run v1.22.17
$ npm run clean && run-p watch:*

> gitpod-website@2.0.0 clean
> run-p clean:*


> gitpod-website@2.0.0 clean:build
> rm -fr ./build


> gitpod-website@2.0.0 clean:css
> rm -f static/global.css && rm -f static/styles.css


> gitpod-website@2.0.0 clean:dev
> rm -fr ./.svelte-kit

$ run-p watch:css:*
$ svelte-kit dev --host 0.0.0.0
$ postcss src/lib/assets/styles.scss -o static/styles.css -w
$ postcss src/lib/assets/global.css -o static/global.css -w
Pre-bundling dependencies:
  svelte
  svelte/store
  js-cookie
  svelte/transition
  svelte/easing
  (...and 5 more)
(this will be run only when your dependencies or config have changed)
 > node_modules/svelte-popperjs/dist/index.es.js:1:29: error: Could not resolve "@popperjs/core" (mark it as external to exclude it from the bundle)
    1 │ import { createPopper } from '@popperjs/core';
      ╵                              ~~~~~~~~~~~~~~~~

> Build failed with 1 error:
node_modules/svelte-popperjs/dist/index.es.js:1:29: error: Could not resolve "@popperjs/core" (mark it as external to exclude it from the bundle)
node_modules/svelte-popperjs/dist/index.es.js:1:29: error: Could not resolve "@popperjs/core" (mark it as external to exclude it from the bundle)
    at failureErrorWithLog (/home/ymo/work/wspace-sites/site-examples/gitpod-io.website.devbr/node_modules/esbuild/lib/main.js:1493:15)
    at /home/ymo/work/wspace-sites/site-examples/gitpod-io.website.devbr/node_modules/esbuild/lib/main.js:1151:28
    at runOnEndCallbacks (/home/ymo/work/wspace-sites/site-examples/gitpod-io.website.devbr/node_modules/esbuild/lib/main.js:941:63)
    at buildResponseToResult (/home/ymo/work/wspace-sites/site-examples/gitpod-io.website.devbr/node_modules/esbuild/lib/main.js:1149:7)
    at /home/ymo/work/wspace-sites/site-examples/gitpod-io.website.devbr/node_modules/esbuild/lib/main.js:1258:14
    at /home/ymo/work/wspace-sites/site-examples/gitpod-io.website.devbr/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/home/ymo/work/wspace-sites/site-examples/gitpod-io.website.devbr/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/home/ymo/work/wspace-sites/site-examples/gitpod-io.website.devbr/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
```

**Comment by pawlean** [comment]
Hey @ymolists. Do you happen to have an example repo that we can take a look at?

**Comment by pawlean** [comment]
Hey @ymolists!

Are you opening our website repo? It should build once you open it on Gitpod. I've not been able to see this error myself, pinging @Cahllagerfeld @nisarhassan12 who may have a better idea.

**Comment by ymolists** [comment]
Hi @pawlean 

I was trying to open this repo locally. I tried opening with gitpod and it ran flawlessly :-)

I am suspecting that it had something to do with using yarn. I will try using only npm and see.

Thank you so much for your help its much appreciated !

**Comment by ymolists** [comment]
I was able to run it in npm. I am not web tech savvy to know what the difference is but i am glad i was able to run it locally at least.

**Comment by Cahllagerfeld** [comment]
Awesome, that it worked 🏀 There might be an issue mixing yarn with npm, as they both have their own lockfile-format.

**Comment by Cahllagerfeld** [comment]
Can this be closed then?
